### ISSUE TITLE
Removed behavior searchandreplace from type Document

### ISSUE THREAD

**Issue by serge73** [collective/collective.searchandreplace#34]
Plone 5.0.5,  s&r 7.1(latest)
./bin/plonectl fg
.......
WARNING plone.dexterity.schema No behavior registration found for behavior named: "collective.searchandreplace.interfaces.ISearchReplaceable" - trying fallback lookup..."
.....
Removed behavior collective.searchandreplace.interfaces.ISearchReplaceable from type Document2016-07-21 13:20:42 ERROR Zope.SiteErrorLog 1469089242.640.267444027251

as a result of the removal behavior - I can't save some of the edited pages

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.edit, line 58, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.dexterity.browser.edit, line 30, in handleApply
  Module z3c.form.group, line 126, in applyChanges
  Module zope.event, line 31, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 585, in subscribers
  Module z3c.relationfield.event, line 76, in updateRelations
  Module zc.relation.catalog, line 546, in unindex
  Module zc.relation.catalog, line 556, in unindex_doc
  Module zc.relation.catalog, line 621, in _remove
KeyError: InterfaceClass Products.CMFDynamicViewFTI.interfaces.ISelectableBrowserDefault

the problem is specific to version 7.x.x

**Comment by Gagaro** [comment]
No issue on my website after going from 6.x to 7.x.

**Comment by serge73** [comment]
You have the behavior of the page in style Types de contenu Dexterity?
Tell me your version of Plone and the version of search and replace from portal_quickinstaller

Behavior removed deliberately?

**Comment by Gagaro** [comment]
c.searchandreplace 7.1.0
plone 5.0.4

Behavior removed by the upgrade step.

**Comment by mauritsvanrees** [comment]
The product was refactored in version 7 to no longer need the behavior (which was introduced in version 6). An upgrade step removes it from all types. In the log that you pasted I see that you have indeed run this upgrade step, so all should be fine.

I tested this before and tried it again now:
- Fresh Plone 5.0.5 site
- Install c.searchandreplace 6.0.4
- Enable the behavior on Document
- Edit the front-page and also create a new Document for good measure.
- Switch to c.searchandreplace master (7.1) and run its upgrade.
- Edit both pages: no problem.

Your traceback ends with the relation catalog trying to remove an item and failing with:

```
KeyError: InterfaceClass Products.CMFDynamicViewFTI.interfaces.ISelectableBrowserDefault
```

That suggests that the problem is not with c.searchandreplace.

Maybe this post helps: http://do3.cc/blog/2012/09/264/debugging-zcrelations---broken-btrees/
At the end you should to do `import transaction; transaction.commit()` otherwise your changes are not saved in this debug session.

Since this seems a zc.relation issue, I have opened a ticket there:
https://github.com/zopefoundation/zc.relation/issues/1

I will close your ticket. If you think it really is a collective.searchandreplace problem, please reopen.
