### ISSUE TITLE
plone 5.1*

### ISSUE THREAD

**Issue by iham** [collective/collective.searchandreplace#37]
running a plone5.1-latest buildout and everything is fine so far.

adding collective.searchandreplace leads to some version pinning issues and getting trough all dependency-pitfalls (we all love buildout for that) i ended up pinnning:

```
zope.publisher = 4.3.2
zope.security = 4.1.1
zope.proxy = 4.2.1
zope.contenttype = 4.2.0
zope.configuration = 4.1.0
zope.browser = 2.1.0
zope.formlib = 4.3.0
```
after that buildout has done its work but now i can't start zope:
```
ZConfig.SchemaResourceError: could not load package ZServer: No module named _base
  Package name: 'ZServer'
  File name: 'component.xml'
  Package path: None
```

so as it seems: no collective.searchandreplace in plone5.1?

p.s.:
i am not shure, if the issue is in the right spot.
but as it was the package, that broke my setup ...

**Comment by mauritsvanrees** [comment]
The dependency issues are because of our `five.formlib` requirement. If we get if of that, the buildout would work without extra pinnings.

But when I add `collective.searchandreplace` to the eggs of the [Plone core development buildout](https://github.com/plone/buildout.coredev) then the buildout finishes correctly and the instance can startup fine. So if you wait for the next 5.1 beta release, it should work.
(Note: I haven't tried to actually use it in 5.1.)
